Исправил недочеты
gusevdaniel/nsu-sdt2020 pull request #1
Opened 2020-10-17 13:57 UTC by gusevdaniel

2020-10-17 16:54 UTC, shishkin-pavel commented on lab1/task_1_2.clj
> +    (recur temp-alphabet (dec temp-n) (connect-words-alphabet result temp-alphabet))
а теперь попробуй заменить это на `iterate`

2020-10-17 16:55 UTC, shishkin-pavel commented
всё ок, попробуй ручную итерацию заменить на нормальный вариан (в образовательных целях), лаба засчитана

2020-10-17 17:00 UTC, shishkin-pavel requested changes

2020-10-17 17:00 UTC, shishkin-pavel commented on lab1/task_1_1.clj
> +    (if (= (last word) (first alphabet))
какова сложность `last`? почему бы не сравнивать first?

2020-10-17 17:00 UTC, shishkin-pavel commented on lab1/task_1_1.clj
> +      (cons (concat word (list (first alphabet))) (connect-word-alphabet word (rest alphabet))))
какова сложность `concat`? почему бы не использовать `(cons (first alphabet) word)`?

2020-10-17 17:24 UTC, gusevdaniel commented on lab1/task_1_2.clj
> +    (recur temp-alphabet (dec temp-n) (connect-words-alphabet result temp-alphabet))
Я данную функцию с помощью iterate сделал в 1.4. Или нужно именно в хвостовой рекурсии?
Вот код из 1.4:
(defn task-1-4 [alphabet n]
  (nth (iterate #(connect-words-alphabet % alphabet) '(())) n))

2020-10-17 17:27 UTC, gusevdaniel commented on lab1/task_1_1.clj
> +    (if (= (last word) (first alphabet))
Использую last, так как word стоит вначале. Впоследствии это дает правильный порядок последовательности.
Также служит для сравнения двух соседних символов:
clj::task-1-1.core=> 
(connect-word-alphabet '(:c) '(:a :b :c))
((:c :a) (:c :b))
clj::task-1-1.core=> 
(connect-word-alphabet '(:c :b) '(:a :b :c))
((:c :b :a) (:c :b :c))

2020-10-17 17:34 UTC, gusevdaniel commented on lab1/task_1_1.clj
> +      (cons (concat word (list (first alphabet))) (connect-word-alphabet word (rest alphabet))))
В данном случае cons и conj ставят word в конец, мне же для правильного порядка надо его добавлять в начало.
Вывод при cons:
(connect-word-alphabet '(:c) '(:a :b :c))
((:a :c) (:b :c))

Вывод при concat:
(connect-word-alphabet '(:c) '(:a :b :c))
((:c :a) (:c :b))

Что в итоге через cons:
(task-1-1 '("a" 1 :b) 2)
((1 "a") (:b "a") ("a" 1) (:b 1) ("a" :b) (1 :b))

И через concat:
(task-1-1 '("a" 1 :b) 2)
(("a" 1) ("a" :b) (1 "a") (1 :b) (:b "a") (:b 1))

2020-10-18 06:28 UTC, shishkin-pavel commented on lab1/task_1_2.clj
> +    (recur temp-alphabet (dec temp-n) (connect-words-alphabet result temp-alphabet))
не нужно, проглядел

2020-10-18 06:31 UTC, shishkin-pavel commented on lab1/task_1_1.clj
> +      (cons (concat word (list (first alphabet))) (connect-word-alphabet word (rest alphabet))))
два замечания, очевидно, связаны, в обоих мы делаем больше операций с целью сохранить более приятный глазу порядок
это далеко не всегда приоритет (+ тут длины списков смешные), так что закрываем задачу, всё ок, можно мерджить =)

2020-10-18 06:34 UTC, merged